-- Copyright (c) .NET Foundation. All rights reserved.
-- Licensed under the MIT License. See License.txt in the project root for license information.

USE [webjobs]
GO

ALTER DATABASE [webjobs] SET ENABLE_BROKER
GO

CREATE MESSAGE TYPE [MT] VALIDATION = NONE
GO

CREATE CONTRACT [C] ([MT] SENT BY INITIATOR)
GO

CREATE QUEUE [SENDERQUEUE] 
GO

-- Retention Off
CREATE QUEUE [RECEIVERQUEUE1] WITH RETENTION = OFF
GO

-- Retention On
CREATE QUEUE [RECEIVERQUEUE2] WITH RETENTION = ON
GO

CREATE SERVICE [SENDERSERVICE] ON QUEUE [SENDERQUEUE] 
GO

CREATE SERVICE [RECEIVERSERVICE1] ON QUEUE [RECEIVERQUEUE1] (C)
GO

CREATE SERVICE [RECEIVERSERVICE2] ON QUEUE [RECEIVERQUEUE2] (C)
GO

GRANT RECEIVE ON [RECEIVERQUEUE1] TO [sqladmin]
GO

GRANT RECEIVE ON [RECEIVERQUEUE2] TO [sqladmin]
GO

