// Copyright (c) .NET Foundation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for license information.

using System;
using System.IO;
using Microsoft.Azure.WebJobs;
using Microsoft.Azure.WebJobs.Extensions.SqlQueue;
using Sample.Extension;

namespace ExtensionsSample
{
    public static class SqlQueueSamples
    {
        public static void SqlQueue_Trigger_Basic([SqlQueueTrigger(DatabaseName = "SqlQueue", QueueName = "RECEIVERQUEUE1", MessageDataType = "VarChar(Max)")] string queueMessage)
        {
            Console.WriteLine("RECEIVERQUEUE1 : " + queueMessage);
        }

        // Note: Param name "messageValue" has to match the metadata generated by SqlQueueTrigger
        // Also, Connection string needs to contain database name as we aren't specifying one here
        public static void SqlQueue_Trigger_With_Metadata([SqlQueueTrigger(QueueName = "RECEIVERQUEUE2")] string queueMessage, SqlQueueTriggerValue messageValue)
        {
            Console.WriteLine("RECEIVERQUEUE2 : " + messageValue);
        }
    }
}
