// Copyright (c) .NET Foundation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for license information.

using System;
using System.IO;
using Microsoft.Azure.WebJobs;
using Microsoft.Azure.WebJobs.Extensions.SqlQueue;
using Sample.Extension;

namespace ExtensionsSample
{
    public static class SqlQueueSamples
    {
        public static void SqlQueue_Trigger_Basic([SqlQueueTrigger(DatabaseName = "webjobs", QueueName = "RECEIVERQUEUE1", ContractName = "C", MessageDataType = "VarChar(Max)")] object queueMessage)
        {
            Console.WriteLine("Message1 : " + queueMessage);
        }

        // Note: Param name "messageValue" has to match the metadata generated by SqlQueueTrigger
        public static void SqlQueue_Trigger_With_Metadata([SqlQueueTrigger( DatabaseName = "webjobs", QueueName = "RECEIVERQUEUE2", ContractName = "C")] object queueMessage, SqlQueueTriggerValue messageValue)
        {
            Console.WriteLine("Message2 : " + messageValue);
        }
    }
}
